name: jdc
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3865
title: Joshua Duchesne Creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181d20'
    - '#f8f6f7'
    - '#454e4d'
    - '#beb9b5'
    - '#8b7b6f'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
