name: jdc
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3865
title: Joshua Duchesne Creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0d161d'
    - '#7b6e68'
    - '#9d9894'
    - '#fcae7f'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
